### ISSUE TITLE
Automatically push empty commit

### ISSUE THREAD

**Issue by qiaochloe** [brown-puzzle-hq/bph-site#163]
Automatically push an empty commit from brown-puzzle-hq on every PR. This should allow us to bypass Vercel's deploy restriction.

**Comment by alex-j-wang** [comment]
No longer necessary, but if needed, do the following:
1. Retrieve the @brown-puzzle-hq PAT from @qiaochloe or @alex-j-wang and create a Repository secret named `PAT_TOKEN` in `Settings → Secrets and variables → Actions`.
2. Copy [dummy-commit.yml](https://github.com/brown-puzzle-hq/2024-puzzlethon-site/blob/main/.github/workflows/dummy-commit.yml) to `.github/workflows/dummy-commit.yml`.
