### ISSUE TITLE
After a failed request on any client, server becomes unable to handle requests from all clients

### ISSUE THREAD

**Issue by brian-xu** [brown-puzzle-hq/bph-site#43]
I attempted to navigate to the admin page via url (localhost:3000/admin). This request failed and resulted in an error page. Afterwards, the server became unable to handle requests from any client (tested on separate browsers). Here's the relevant error: 
``` ⨯ ./src/app/admin/components/HintTable.tsx:3:1
Module not found: Can't resolve '@tanstack/react-table'
   1 | "use client";
   2 |
>  3 | import {
     | ^^^^^^^^
>  4 |   ColumnDef,
     | ^^^^^^^^^^^^
>  5 |   ColumnFiltersState,
     | ^^^^^^^^^^^^
>  6 |   flexRender,
     | ^^^^^^^^^^^^
>  7 |   getCoreRowModel,
     | ^^^^^^^^^^^^
>  8 |   getPaginationRowModel,
     | ^^^^^^^^^^^^
>  9 |   getFilteredRowModel,
     | ^^^^^^^^^^^^
> 10 |   useReactTable,
     | ^^^^^^^^^^^^
> 11 | } from "@tanstack/react-table";
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  12 |
  13 | import {
  14 |   Table,```

**Comment by brian-xu** [comment]
ok so the specific error above is my fault for not running `npm install` after pulling, but the problem persists across all pages/clients so it's still probably worth looking itno

**Comment by qiaochloe** [comment]
Going to reopen this, since I feel like it was never fully resolved. I'm getting the "Cannot read proprieties on null (useContext) error" all the time.

**Comment by qiaochloe** [comment]
Closing this again, not replicable and not sure it will be resolved.
